spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  data:
    redis:
      host: 127.0.0.1  # Redis 서버의 호스트 주소를 설정합니다. 여기서는 로컬 호스트(127.0.0.1)를 사용합니다.
      port: 6379       # Redis 서버가 수신 대기하는 포트를 설정합니다. Redis의 기본 포트는 6379입니다.
  jpa:
    hibernate:
      ddl-auto: update  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 300000
  refresh-token-expiration-minutes: 5000000